### ISSUE TITLE
[요청] 아키텍쳐 그림 관련 자료들 요청드립니다.

### ISSUE THREAD

**Issue by keenranger** [aws-samples/generative-ai-demo-using-amazon-sagemaker-jumpstart-kr#2]
안녕하세요,
아까 현장에서 주신 설명, 정말 감사합니다. 그리고 이렇게 자료를 공개해주신 것도 너무 감사드립니다.
혹시 기회가 되신다면, summit 때에 보여주신 아키텍처 그림도 함께 게시해주실 수 있을까요?  
감사합니다.

**Comment by LecterSnap** [comment]
> 안녕하세요, 아까 현장에서 주신 설명, 정말 감사합니다. 그리고 이렇게 자료를 공개해주신 것도 너무 감사드립니다. 혹시 기회가 되신다면, summit 때에 보여주신 아키텍처 그림도 함께 게시해주실 수 있을까요? 감사합니다.

말씀하신대로 Summit 때 공개한 전체 아키텍처에 대한 설명자료도 업데이트 예정입니다. 관심가져주셔서 감사합니다 :)

**Comment by keenranger** [comment]
updated 263d6ba
